#!/usr/bin/env python3
"""Generate CONNECTOR_STATUS.md from probe result JSON files."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DOMAIN_PROBE = REPO / "docs" / "catalog_domain_probe.json"
CONNECTOR_PROBE = REPO / "docs" / "connector_probe_results.json"
OUTPUT = REPO / "docs" / "CONNECTOR_STATUS.md"

HANDCRAFTED = frozenset({
    "mangadex", "asurascans", "mangakatana", "demonicscans", "coffeemanga",
    "nhentai", "18porncomic", "3hentai", "8muses", "akuma", "1stkissmanga",
})


def _load(path: Path) -> dict | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> None:
    domain = _load(DOMAIN_PROBE) or {"results": [], "counts": {}, "probed_at": "n/a"}
    connector = _load(CONNECTOR_PROBE) or {"results": [], "live": 0, "dead": 0, "probed_at": "n/a"}

    domain_by_id = {r["source_id"]: r for r in domain["results"]}
    connector_by_id = {r["source_id"]: r for r in connector["results"]}

    all_ids = sorted(set(domain_by_id) | set(connector_by_id) | HANDCRAFTED)

    lines = [
        "# Connector rollout tracker",
        "",
        "Auto-generated by `backend/scripts/generate_connector_status.py`.",
        "",
        "## Status legend",
        "",
        "| Status | Meaning |",
        "|--------|---------|",
        "| `LIVE` | Connector browse returns series |",
        "| `TRUE_MADARA` | Domain responds with Madara HTML (factory candidate) |",
        "| `CUSTOM_NEEDED` | Site responds but needs dedicated connector |",
        "| `DEAD` | Empty listing / HTTP error after connector probe |",
        "| `UNREACHABLE` | DNS / TLS / timeout at domain probe |",
        "| `HANDCRAFTED` | Dedicated connector package (not Madara factory) |",
        "| `SKIPPED` | Never register (Comick excluded permanently) |",
        "",
        "## 3-strike rule",
        "",
        "A source is **skipped** (not re-attempted each batch) when:",
        "",
        "1. Domain probe = `DEAD` or `UNREACHABLE`, **and**",
        "2. Connector probe = `DEAD` or `ERROR`, **and**",
        "3. Combined failures ≥ **3** probe runs (tracked in JSON `strikes` fields).",
        "",
        "Re-probe skipped sources with:",
        "",
        "```bash",
        "cd backend && .venv/bin/python scripts/probe_catalog_domains.py --retry-dead",
        "cd backend && .venv/bin/python scripts/probe_all_connectors.py --retry-dead",
        "```",
        "",
        f"## Probe snapshots",
        "",
        f"- Domain structure: `{DOMAIN_PROBE.name}` — {domain.get('probed_at', 'n/a')}",
        f"- Connector browse: `{CONNECTOR_PROBE.name}` — {connector.get('probed_at', 'n/a')}",
        f"- Connector totals: {connector.get('live', '?')} LIVE / {connector.get('dead', '?')} DEAD",
        "",
        f"## Full catalog ({len(all_ids)} sources)",
        "",
        "| ID | Domain | Domain class | Connector | Items | Strikes | Notes |",
        "|----|--------|--------------|-----------|-------|---------|-------|",
    ]

    for sid in all_ids:
        d = domain_by_id.get(sid, {})
        c = connector_by_id.get(sid, {})
        domain_class = d.get("classification", "—")
        conn_status = c.get("status", "—")
        items = c.get("items", "")
        strikes = max(d.get("strikes", 0), 0)
        if conn_status == "DEAD":
            strikes = max(strikes, 1)
        domain_name = d.get("domain", "—")
        note = (c.get("detail") or d.get("detail") or "")[:60]
        if sid == "comick":
            domain_class = "SKIPPED"
            conn_status = "SKIPPED"
            note = "excluded permanently"
        lines.append(
            f"| {sid} | {domain_name} | {domain_class} | {conn_status} | {items} | {strikes} | {note} |"
        )

    lines.extend(
        [
            "",
            "## Excluded permanently",
            "",
            "- **Comick** — product decision, never register.",
            "",
            "## Re-probe commands",
            "",
            "```bash",
            "cd backend && .venv/bin/python scripts/probe_catalog_domains.py",
            "cd backend && .venv/bin/python scripts/probe_all_connectors.py",
            "cd backend && .venv/bin/python scripts/generate_connector_status.py",
            "```",
            "",
            f"_Generated {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}_",
            "",
        ]
    )

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(all_ids)} rows)")


if __name__ == "__main__":
    main()
