/*
 * themes.generated.ts — GENERATED, do not edit.
 *
 * Source:    https://github.com/tinted-theming/schemes
 * Revision:  fdca32a0d14ec80ad83a78a9ccb85592ca6cb9e1
 * Regenerate: node scripts/themes/build-themes.mjs
 *
 * 38 palettes, mapped from base16 by scripts/themes/map.mjs and gated at
 * WCAG AA. 227 of the corpus's 338 schemes clear the gate;
 * scripts/themes/curated.mjs picks which of those are worth a tile.
 */

import type { GeneratedThemeMeta } from "./theme-types";

/**
 * Ordered dark-first, and within a variant in the order `curated.mjs` declares
 * — which groups families together (every Gruvbox next to every other) rather
 * than alphabetising them apart.
 *
 * `as const satisfies` rather than a plain annotation: the ids have to survive
 * as literal types so `ReadingTheme` stays a closed union and a typo in a
 * `setTheme("gruvbux")` call is a compile error rather than a theme that does
 * nothing.
 */
export const GENERATED_THEMES = [
  {
    id: "gruvbox-dark-hard",
    label: "Gruvbox Hard",
    description: "Retro warmth — burnt orange and olive on deep brown.",
    author: "Dawid Kurek, morhetz",
    scheme: "dark",
    swatch: {
      bg: "#1D2021",
      surface: "#47423D",
      fg: "#D5C4A1",
      muted: "#BDAE93",
      accent: "#FABD2F",
    },
  },
  {
    id: "gruvbox-dark-medium",
    label: "Gruvbox",
    description: "The classic: softer ground than Hard, same earth tones.",
    author: "Dawid Kurek, morhetz",
    scheme: "dark",
    swatch: {
      bg: "#282828",
      surface: "#47423D",
      fg: "#D5C4A1",
      muted: "#BDAE93",
      accent: "#FABD2F",
    },
  },
  {
    id: "gruvbox-material-dark-medium",
    label: "Gruvbox Material",
    description: "Gruvbox with the saturation pulled back for long sessions.",
    author: "Mayush Kumar, sainnhe",
    scheme: "dark",
    swatch: {
      bg: "#292828",
      surface: "#3E3B37",
      fg: "#DDC7A1",
      muted: "#BDAE93",
      accent: "#83B1A5",
    },
  },
  {
    id: "nord",
    label: "Nord",
    description: "Arctic blue-greys with frost and aurora accents.",
    author: "arcticicestudio",
    scheme: "dark",
    swatch: {
      bg: "#2E3440",
      surface: "#434C5E",
      fg: "#E5E9F0",
      muted: "#B7BDC8",
      accent: "#EBCB8B",
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    description: "Purple and pink on deep indigo. The famous one.",
    author: "clach04",
    scheme: "dark",
    swatch: {
      bg: "#282A36",
      surface: "#40424C",
      fg: "#F8F8F2",
      muted: "#A6AEC7",
      accent: "#C49EFA",
    },
  },
  {
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    description: "Pastel mauve and sky on a soft near-black.",
    author: "catppuccin",
    scheme: "dark",
    swatch: {
      bg: "#1E1E2E",
      surface: "#313244",
      fg: "#CDD6F4",
      muted: "#979DB6",
      accent: "#89B4FA",
    },
  },
  {
    id: "catppuccin-macchiato",
    label: "Catppuccin Macchiato",
    description: "Mocha's warmer, slightly lighter sibling.",
    author: "catppuccin",
    scheme: "dark",
    swatch: {
      bg: "#24273A",
      surface: "#363A4F",
      fg: "#CAD3F5",
      muted: "#9DA4C2",
      accent: "#8AADF4",
    },
  },
  {
    id: "rose-pine",
    label: "Rosé Pine",
    description: "Muted rose and pine on a deep plum night.",
    author: "Emilia Dunfelt",
    scheme: "dark",
    swatch: {
      bg: "#191724",
      surface: "#26233A",
      fg: "#E0DEF4",
      muted: "#908CAA",
      accent: "#C4A7E7",
    },
  },
  {
    id: "rose-pine-moon",
    label: "Rosé Pine Moon",
    description: "Rosé Pine lifted off black, gentler at night.",
    author: "Emilia Dunfelt",
    scheme: "dark",
    swatch: {
      bg: "#232136",
      surface: "#393552",
      fg: "#E0DEF4",
      muted: "#A7A4BD",
      accent: "#C4A7E7",
    },
  },
  {
    id: "kanagawa",
    label: "Kanagawa",
    description: "Ink-wash blues and dry gold, after Hokusai.",
    author: "Tommaso Laurenzi",
    scheme: "dark",
    swatch: {
      bg: "#1F1F28",
      surface: "#223249",
      fg: "#DCD7BA",
      muted: "#9F9C97",
      accent: "#7E9CD8",
    },
  },
  {
    id: "everforest-dark-hard",
    label: "Everforest",
    description: "Low-saturation forest greens, easy on tired eyes.",
    author: "Sainnhe Park",
    scheme: "dark",
    swatch: {
      bg: "#272E33",
      surface: "#3A4244",
      fg: "#D3C6AA",
      muted: "#B0AF9B",
      accent: "#7FBBB3",
    },
  },
  {
    id: "tokyo-city-dark",
    label: "Tokyo City",
    description: "Neon-on-navy in the Tokyo Night lineage.",
    author: "Michaël Ball",
    scheme: "dark",
    swatch: {
      bg: "#171D23",
      surface: "#28323A",
      fg: "#D8E2EC",
      muted: "#B7C5D3",
      accent: "#7AA2F7",
    },
  },
  {
    id: "ayu-dark",
    label: "Ayu Dark",
    description: "Warm amber on charcoal — sharp and modern.",
    author: "Tinted Theming, Ayu Theme",
    scheme: "dark",
    swatch: {
      bg: "#0B0E14",
      surface: "#202229",
      fg: "#E6E1CF",
      muted: "#BFBDB6",
      accent: "#59C2FF",
    },
  },
  {
    id: "ayu-mirage",
    label: "Ayu Mirage",
    description: "Ayu on slate-blue, one stop lighter.",
    author: "Tinted Theming, Ayu Theme",
    scheme: "dark",
    swatch: {
      bg: "#1F2430",
      surface: "#323844",
      fg: "#CCCAC2",
      muted: "#A5A5A3",
      accent: "#73D0FF",
    },
  },
  {
    id: "onedark-dark",
    label: "One Dark",
    description: "Atom's default, and half the internet's.",
    author: "olimorris",
    scheme: "dark",
    swatch: {
      bg: "#000000",
      surface: "#26292F",
      fg: "#ABB2BF",
      muted: "#8C929E",
      accent: "#61AFEF",
    },
  },
  {
    id: "monokai",
    label: "Monokai",
    description: "Sublime's green, pink and orange on graphite.",
    author: "Wimer Hazenberg",
    scheme: "dark",
    swatch: {
      bg: "#272822",
      surface: "#45453E",
      fg: "#F8F8F2",
      muted: "#B7B5A8",
      accent: "#66D9EF",
    },
  },
  {
    id: "material-darker",
    label: "Material",
    description: "Teal and coral on true dark grey.",
    author: "Nate Peterson",
    scheme: "dark",
    swatch: {
      bg: "#212121",
      surface: "#353535",
      fg: "#EEFFFF",
      muted: "#B2CCD6",
      accent: "#82AAFF",
    },
  },
  {
    id: "github-dark",
    label: "GitHub Dark",
    description: "GitHub's own dark mode, familiar and neutral.",
    author: "Tinted Theming",
    scheme: "dark",
    swatch: {
      bg: "#0D1117",
      surface: "#23282F",
      fg: "#C9D1D9",
      muted: "#8B949E",
      accent: "#D2A8FF",
    },
  },
  {
    id: "flexoki-dark",
    label: "Flexoki Dark",
    description: "Ink-and-paper pigments tuned for E Ink.",
    author: "Steph Ango",
    scheme: "dark",
    swatch: {
      bg: "#100F0F",
      surface: "#282726",
      fg: "#CECDC3",
      muted: "#93928B",
      accent: "#5F97C6",
    },
  },
  {
    id: "oxocarbon-dark",
    label: "Oxocarbon",
    description: "IBM Carbon — cool blue with electric magenta.",
    author: "shaunsingh/IBM, Tinted Theming",
    scheme: "dark",
    swatch: {
      bg: "#161616",
      surface: "#343435",
      fg: "#F2F4F8",
      muted: "#A2A3A5",
      accent: "#33B1FF",
    },
  },
  {
    id: "spaceduck",
    label: "Spaceduck",
    description: "Deep space navy with cyan and violet instruments.",
    author: "Guillermo Rodriguez, packaged by Gabriel Fontes",
    scheme: "dark",
    swatch: {
      bg: "#16172D",
      surface: "#2A2B40",
      fg: "#ECF0C1",
      muted: "#9096A6",
      accent: "#F2CE00",
    },
  },
  {
    id: "eldritch",
    label: "Eldritch",
    description: "Occult greens and purples on abyssal blue.",
    author: "eldritch-theme",
    scheme: "dark",
    swatch: {
      bg: "#212337",
      surface: "#3F4255",
      fg: "#EBFAFA",
      muted: "#A1B1E1",
      accent: "#39DDFD",
    },
  },
  {
    id: "selenized-black",
    label: "Selenized Black",
    description: "Solarized's successor, rebuilt for true black.",
    author: "Jan Warchol / adapted to base16 by ali",
    scheme: "dark",
    swatch: {
      bg: "#181818",
      surface: "#2F2F2F",
      fg: "#B9B9B9",
      muted: "#989898",
      accent: "#DBB32D",
    },
  },
  {
    id: "horizon-dark",
    label: "Horizon Dark",
    description: "Dusk pinks and corals over a warm slate.",
    author: "Michaël Ball",
    scheme: "dark",
    swatch: {
      bg: "#1C1E26",
      surface: "#2E303E",
      fg: "#CBCED0",
      muted: "#9DA0A2",
      accent: "#EFB993",
    },
  },
  {
    id: "zenburn",
    label: "Zenburn",
    description: "The low-contrast original: sage and rust on grey.",
    author: "elnawe",
    scheme: "dark",
    swatch: {
      bg: "#383838",
      surface: "#4B4B4A",
      fg: "#DCDCCC",
      muted: "#BBBBB0",
      accent: "#E0CF9F",
    },
  },
  {
    id: "vesper",
    label: "Vesper",
    description: "Near-monochrome graphite with a single amber note.",
    author: "FormalSnake",
    scheme: "dark",
    swatch: {
      bg: "#101010",
      surface: "#2D2D2D",
      fg: "#B7B7B7",
      muted: "#999999",
      accent: "#8EAAAA",
    },
  },
  {
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    description: "Pastel accents on cool porcelain.",
    author: "catppuccin",
    scheme: "light",
    swatch: {
      bg: "#EFF1F5",
      surface: "#FBFBFC",
      fg: "#4C4F69",
      muted: "#686B82",
      accent: "#2364E7",
    },
  },
  {
    id: "rose-pine-dawn",
    label: "Rosé Pine Dawn",
    description: "Warm blush paper with muted rose ink.",
    author: "Emilia Dunfelt",
    scheme: "light",
    swatch: {
      bg: "#FAF4ED",
      surface: "#FEFCFA",
      fg: "#575279",
      muted: "#716C8B",
      accent: "#286983",
    },
  },
  {
    id: "gruvbox-light-medium",
    label: "Gruvbox Light",
    description: "Cream paper, earth-tone ink.",
    author: "Dawid Kurek, morhetz",
    scheme: "light",
    swatch: {
      bg: "#FBF1C7",
      surface: "#FEFBEF",
      fg: "#504945",
      muted: "#665C54",
      accent: "#076678",
    },
  },
  {
    id: "one-light",
    label: "One Light",
    description: "One Dark inverted — crisp, neutral, familiar.",
    author: "Daniel Pfeifer",
    scheme: "light",
    swatch: {
      bg: "#FAFAFA",
      surface: "#EAEAEA",
      fg: "#383A42",
      muted: "#67686F",
      accent: "#A626A4",
    },
  },
  {
    id: "github",
    label: "GitHub Light",
    description: "GitHub's default: plain white and a confident blue.",
    author: "Tinted Theming",
    scheme: "light",
    swatch: {
      bg: "#FFFFFF",
      surface: "#EFF0F0",
      fg: "#424A53",
      muted: "#636C75",
      accent: "#7D4ED6",
    },
  },
  {
    id: "flexoki-light",
    label: "Flexoki Light",
    description: "Warm paper pigments; the E Ink palette by daylight.",
    author: "Steph Ango",
    scheme: "light",
    swatch: {
      bg: "#FFFCF0",
      surface: "#EFECE1",
      fg: "#403E3C",
      muted: "#6B6965",
      accent: "#205EA6",
    },
  },
  {
    id: "nord-light",
    label: "Nord Light",
    description: "Arctic blues on snow.",
    author: "threddast, based on fuxialexander's doom-nord-light-theme (Doom Emacs)",
    scheme: "light",
    swatch: {
      bg: "#E5E9F0",
      surface: "#F8F9FB",
      fg: "#2E3440",
      muted: "#5B6372",
      accent: "#3A6BA3",
    },
  },
  {
    id: "tokyo-night-light",
    label: "Tokyo Night Light",
    description: "The night city at noon — indigo ink on white.",
    author: "Michaël Ball",
    scheme: "light",
    swatch: {
      bg: "#D5D6DB",
      surface: "#F3F4F5",
      fg: "#343B59",
      muted: "#4C505E",
      accent: "#34548A",
    },
  },
  {
    id: "selenized-white",
    label: "Selenized White",
    description: "Solarized's successor at full brightness.",
    author: "Jan Warchol / adapted to base16 by ali",
    scheme: "light",
    swatch: {
      bg: "#FFFFFF",
      surface: "#EFEFEF",
      fg: "#474747",
      muted: "#6A6A6A",
      accent: "#0054CF",
    },
  },
  {
    id: "equilibrium-light",
    label: "Equilibrium Light",
    description: "Warm oat paper balanced against a cool blue.",
    author: "Carlo Abelli",
    scheme: "light",
    swatch: {
      bg: "#F5F0E7",
      surface: "#FCFBF8",
      fg: "#43474E",
      muted: "#5A5F66",
      accent: "#016FAE",
    },
  },
  {
    id: "horizon-light",
    label: "Horizon Light",
    description: "Dawn corals and pinks on warm off-white.",
    author: "Michaël Ball",
    scheme: "light",
    swatch: {
      bg: "#FDF0ED",
      surface: "#FEFBFA",
      fg: "#403C3D",
      muted: "#726C6B",
      accent: "#DA103F",
    },
  },
  {
    id: "sakura",
    label: "Sakura",
    description: "Blossom pink paper with deep teal ink.",
    author: "Misterio77",
    scheme: "light",
    swatch: {
      bg: "#FEEDF3",
      surface: "#FFFAFC",
      fg: "#564448",
      muted: "#755F64",
      accent: "#006E93",
    },
  },
] as const satisfies readonly GeneratedThemeMeta[];
