"""reading profiles table

Adds the ``reading_profiles`` table: several lightweight, ordered, themed
profiles per account (Netflix-style). Unlike the legacy per-user-state tables
this is new, so ``user_id`` is NOT NULL and deletes cascade with the owning
account (``ON DELETE CASCADE``). Indexed by ``user_id`` and by
``(user_id, sort_order)`` to serve the ordered per-user profile list.

Revision ID: c29b60ed8738
Revises: efe6a4dc459e
Create Date: 2026-07-12 00:12:01.008753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29b60ed8738'
down_revision: Union[str, Sequence[str], None] = 'efe6a4dc459e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_key', sa.String(length=64), nullable=False),
    sa.Column('mood', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_reading_profiles_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_reading_profiles_user_sort', ['user_id', 'sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_reading_profiles_user_sort')
        batch_op.drop_index('ix_reading_profiles_user_id')

    op.drop_table('reading_profiles')
    # ### end Alembic commands ###
