"""baseline schema (phase-1)

Revision ID: c2b7350c254a
Revises: 
Create Date: 2026-07-11 15:05:36.849877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b7350c254a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_path', sa.String(length=1024), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index('ix_collection_sort_order', ['sort_order'], unique=False)

    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('root_path', sa.String(length=1024), nullable=False),
    sa.Column('scan_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_path')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('update_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('series_checked', sa.Integer(), nullable=False),
    sa.Column('new_chapters_found', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('update_runs', schema=None) as batch_op:
        batch_op.create_index('ix_update_runs_started_at', ['started_at'], unique=False)

    op.create_table('update_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('notify_enabled', sa.Integer(), nullable=False),
    sa.Column('auto_download_enabled', sa.Integer(), nullable=False),
    sa.Column('check_on_startup', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_username', ['username'], unique=False)

    op.create_table('import_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('folder_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('series_count', sa.Integer(), nullable=False),
    sa.Column('chapter_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_history', schema=None) as batch_op:
        batch_op.create_index('ix_import_history_library_id', ['library_id'], unique=False)

    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('cover_path', sa.String(length=1024), nullable=True),
    sa.Column('folder_path', sa.String(length=1024), nullable=False),
    sa.Column('sort_title', sa.String(length=512), nullable=False),
    sa.Column('original_title', sa.String(length=512), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('content_rating', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Integer(), nullable=False),
    sa.Column('reading_status', sa.String(length=64), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('read_chapters', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('is_created', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_path', name='uq_series_folder_path')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index('ix_series_author_sort', ['author', 'sort_title'], unique=False)
        batch_op.create_index('ix_series_content_rating', ['content_rating'], unique=False)
        batch_op.create_index('ix_series_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_series_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_series_is_favorite', ['is_favorite'], unique=False)
        batch_op.create_index('ix_series_language_sort', ['language', 'sort_title'], unique=False)
        batch_op.create_index('ix_series_library_id', ['library_id'], unique=False)
        batch_op.create_index('ix_series_live', ['library_id', 'sort_title'], unique=False)
        batch_op.create_index('ix_series_reading_status', ['reading_status'], unique=False)
        batch_op.create_index('ix_series_sort_title', ['sort_title'], unique=False)
        batch_op.create_index('ix_series_status_sort', ['status', 'sort_title'], unique=False)
        batch_op.create_index('ix_series_title', ['title'], unique=False)
        batch_op.create_index('ix_series_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_series_year_sort', ['year'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_sessions_token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_sessions_token_hash', ['token_hash'], unique=False)
        batch_op.create_index('ix_sessions_user_id', ['user_id'], unique=False)

    op.create_table('collection_series',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'series_id')
    )
    with op.batch_alter_table('collection_series', schema=None) as batch_op:
        batch_op.create_index('ix_collection_series_series_id', ['series_id'], unique=False)

    op.create_table('series_tags',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('is_ai_generated', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'tag_id')
    )
    with op.batch_alter_table('series_tags', schema=None) as batch_op:
        batch_op.create_index('ix_series_tags_tag_id', ['tag_id'], unique=False)

    op.create_table('series_trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('series_id', sa.String(length=128), nullable=False),
    sa.Column('series_title', sa.String(length=512), nullable=False),
    sa.Column('track_kind', sa.String(length=32), nullable=False),
    sa.Column('local_series_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('notify', sa.Integer(), nullable=False),
    sa.Column('auto_download', sa.Integer(), nullable=False),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('known_chapter_ids', sa.Text(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['local_series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'series_id', 'track_kind', name='uq_series_tracker')
    )
    with op.batch_alter_table('series_trackers', schema=None) as batch_op:
        batch_op.create_index('ix_series_trackers_enabled', ['enabled'], unique=False)
        batch_op.create_index('ix_series_trackers_source', ['source'], unique=False)
        batch_op.create_index('ix_series_trackers_track_kind', ['track_kind'], unique=False)

    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('cover_path', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volumes', schema=None) as batch_op:
        batch_op.create_index('ix_volumes_series_id', ['series_id'], unique=False)

    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('volume_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('number', sa.Float(), nullable=True),
    sa.Column('folder_path', sa.String(length=1024), nullable=True),
    sa.Column('archive_path', sa.String(length=1024), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('cover_path', sa.String(length=1024), nullable=True),
    sa.Column('sort_key', sa.String(length=32), nullable=False),
    sa.Column('is_read', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'folder_path', name='uq_chapter_series_folder')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index('ix_chapters_folder_path', ['folder_path'], unique=False)
        batch_op.create_index('ix_chapters_is_read', ['is_read'], unique=False)
        batch_op.create_index('ix_chapters_read_at', ['read_at'], unique=False)
        batch_op.create_index('ix_chapters_series_id', ['series_id'], unique=False)
        batch_op.create_index('ix_chapters_series_sort', ['series_id', 'sort_key'], unique=False)

    op.create_table('update_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('series_id', sa.String(length=128), nullable=False),
    sa.Column('series_title', sa.String(length=512), nullable=False),
    sa.Column('chapter_id', sa.String(length=128), nullable=False),
    sa.Column('chapter_title', sa.String(length=512), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tracker_id'], ['series_trackers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('update_notifications', schema=None) as batch_op:
        batch_op.create_index('ix_update_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_update_notifications_is_read', ['is_read'], unique=False)
        batch_op.create_index('ix_update_notifications_tracker_id', ['tracker_id'], unique=False)

    op.create_table('chapter_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('last_page', sa.Integer(), nullable=False),
    sa.Column('scroll_offset_px', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id')
    )
    with op.batch_alter_table('chapter_progress', schema=None) as batch_op:
        batch_op.create_index('ix_chapter_progress_chapter_id', ['chapter_id'], unique=False)

    op.create_table('chapter_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', name='uq_chapter_texts_chapter_id')
    )
    with op.batch_alter_table('chapter_texts', schema=None) as batch_op:
        batch_op.create_index('ix_chapter_texts_chapter_id', ['chapter_id'], unique=False)

    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('series_id', sa.String(length=128), nullable=False),
    sa.Column('chapter_id', sa.String(length=128), nullable=False),
    sa.Column('series_title', sa.String(length=512), nullable=False),
    sa.Column('chapter_title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('pages_done', sa.Integer(), nullable=False),
    sa.Column('pages_total', sa.Integer(), nullable=False),
    sa.Column('bytes_downloaded', sa.Integer(), nullable=False),
    sa.Column('local_chapter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['local_chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.create_index('ix_downloads_source_series_chapter', ['source', 'series_id', 'chapter_id'], unique=False)
        batch_op.create_index('ix_downloads_status', ['status'], unique=False)

    op.create_table('ocr_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('pages_done', sa.Integer(), nullable=False),
    sa.Column('pages_total', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_ocr_jobs_chapter_id', ['chapter_id'], unique=False)
        batch_op.create_index('ix_ocr_jobs_status', ['status'], unique=False)
        batch_op.create_index('ix_ocr_jobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index('ix_pages_chapter_id', ['chapter_id'], unique=False)

    op.create_table('reading_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('last_page', sa.Integer(), nullable=False),
    sa.Column('scroll_offset_px', sa.Integer(), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id')
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_index('ix_reading_progress_last_read', ['last_read_at'], unique=False)
        batch_op.create_index('ix_reading_progress_series_id', ['series_id'], unique=False)

    op.create_table('reading_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('pages_read', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_reading_sessions_chapter_id', ['chapter_id'], unique=False)
        batch_op.create_index('ix_reading_sessions_series_id', ['series_id'], unique=False)
        batch_op.create_index('ix_reading_sessions_started_at', ['started_at'], unique=False)
        batch_op.create_index('ix_reading_sessions_started_series', ['started_at', 'series_id'], unique=False)

    op.create_table('source_chapter_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('series_id', sa.String(length=128), nullable=False),
    sa.Column('chapter_id', sa.String(length=128), nullable=False),
    sa.Column('local_chapter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['local_chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'series_id', 'chapter_id', name='uq_source_chapter')
    )
    with op.batch_alter_table('source_chapter_links', schema=None) as batch_op:
        batch_op.create_index('ix_source_chapter_links_local', ['local_chapter_id'], unique=False)

    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index('ix_bookmarks_series_id', ['series_id'], unique=False)

    op.create_table('download_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('download_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['download_id'], ['downloads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('download_id')
    )
    with op.batch_alter_table('download_queue', schema=None) as batch_op:
        batch_op.create_index('ix_download_queue_state_priority', ['state', 'priority'], unique=False)

    op.create_table('page_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('boxes', sa.Text(), nullable=True),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', name='uq_page_texts_page_id')
    )
    with op.batch_alter_table('page_texts', schema=None) as batch_op:
        batch_op.create_index('ix_page_texts_page_id', ['page_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_texts', schema=None) as batch_op:
        batch_op.drop_index('ix_page_texts_page_id')

    op.drop_table('page_texts')
    with op.batch_alter_table('download_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_download_queue_state_priority')

    op.drop_table('download_queue')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index('ix_bookmarks_series_id')

    op.drop_table('bookmarks')
    with op.batch_alter_table('source_chapter_links', schema=None) as batch_op:
        batch_op.drop_index('ix_source_chapter_links_local')

    op.drop_table('source_chapter_links')
    with op.batch_alter_table('reading_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_reading_sessions_started_series')
        batch_op.drop_index('ix_reading_sessions_started_at')
        batch_op.drop_index('ix_reading_sessions_series_id')
        batch_op.drop_index('ix_reading_sessions_chapter_id')

    op.drop_table('reading_sessions')
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_reading_progress_series_id')
        batch_op.drop_index('ix_reading_progress_last_read')

    op.drop_table('reading_progress')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index('ix_pages_chapter_id')

    op.drop_table('pages')
    with op.batch_alter_table('ocr_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_ocr_jobs_status_created')
        batch_op.drop_index('ix_ocr_jobs_status')
        batch_op.drop_index('ix_ocr_jobs_chapter_id')

    op.drop_table('ocr_jobs')
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_index('ix_downloads_status')
        batch_op.drop_index('ix_downloads_source_series_chapter')

    op.drop_table('downloads')
    with op.batch_alter_table('chapter_texts', schema=None) as batch_op:
        batch_op.drop_index('ix_chapter_texts_chapter_id')

    op.drop_table('chapter_texts')
    with op.batch_alter_table('chapter_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_chapter_progress_chapter_id')

    op.drop_table('chapter_progress')
    with op.batch_alter_table('update_notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_update_notifications_tracker_id')
        batch_op.drop_index('ix_update_notifications_is_read')
        batch_op.drop_index('ix_update_notifications_created_at')

    op.drop_table('update_notifications')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index('ix_chapters_series_sort')
        batch_op.drop_index('ix_chapters_series_id')
        batch_op.drop_index('ix_chapters_read_at')
        batch_op.drop_index('ix_chapters_is_read')
        batch_op.drop_index('ix_chapters_folder_path')

    op.drop_table('chapters')
    with op.batch_alter_table('volumes', schema=None) as batch_op:
        batch_op.drop_index('ix_volumes_series_id')

    op.drop_table('volumes')
    with op.batch_alter_table('series_trackers', schema=None) as batch_op:
        batch_op.drop_index('ix_series_trackers_track_kind')
        batch_op.drop_index('ix_series_trackers_source')
        batch_op.drop_index('ix_series_trackers_enabled')

    op.drop_table('series_trackers')
    with op.batch_alter_table('series_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_series_tags_tag_id')

    op.drop_table('series_tags')
    with op.batch_alter_table('collection_series', schema=None) as batch_op:
        batch_op.drop_index('ix_collection_series_series_id')

    op.drop_table('collection_series')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_id')
        batch_op.drop_index('ix_sessions_token_hash')
        batch_op.drop_index('ix_sessions_expires_at')

    op.drop_table('sessions')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index('ix_series_year_sort')
        batch_op.drop_index('ix_series_updated_at')
        batch_op.drop_index('ix_series_title')
        batch_op.drop_index('ix_series_status_sort')
        batch_op.drop_index('ix_series_sort_title')
        batch_op.drop_index('ix_series_reading_status')
        batch_op.drop_index('ix_series_live')
        batch_op.drop_index('ix_series_library_id')
        batch_op.drop_index('ix_series_language_sort')
        batch_op.drop_index('ix_series_is_favorite')
        batch_op.drop_index('ix_series_deleted_at')
        batch_op.drop_index('ix_series_created_at')
        batch_op.drop_index('ix_series_content_rating')
        batch_op.drop_index('ix_series_author_sort')

    op.drop_table('series')
    with op.batch_alter_table('import_history', schema=None) as batch_op:
        batch_op.drop_index('ix_import_history_library_id')

    op.drop_table('import_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')

    op.drop_table('users')
    op.drop_table('update_settings')
    with op.batch_alter_table('update_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_update_runs_started_at')

    op.drop_table('update_runs')
    op.drop_table('tags')
    op.drop_table('libraries')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index('ix_collection_sort_order')

    op.drop_table('collections')
    # ### end Alembic commands ###
