// GENERATED by tool/themes/build_palettes.dart — do not edit.
//
// Source:     tinted-theming/schemes @ fdca32a0d14ec80ad83a78a9ccb85592ca6cb9e1
// Mapped by:  frontend/scripts/themes/map.mjs (via its output)
// Regenerate: dart run tool/themes/build_palettes.dart
import 'package:flutter/material.dart';
import 'package:manhwamaniacs/app/theme/app_palette.dart';

/// The base16 palettes, converted from the set the web app
/// ships so a scheme wears the same colours on both.
///
/// Every entry cleared the floors in
/// `test/app/theme/palette_contrast_test.dart` at generation
/// time; the suite re-checks them on every run.
abstract final class Base16Palettes {
  /// Gruvbox Hard — Dawid Kurek, morhetz.
  ///
  /// Retro warmth — burnt orange and olive on deep brown.
  ///
  /// Worst pairing: danger on surface at 3.37:1.
  static const AppPalette gruvbox = AppPalette(
    id: 'gruvbox',
    name: 'Gruvbox Hard',
    description: 'Retro warmth — burnt orange and olive on deep brown.',
    author: 'Dawid Kurek, morhetz',
    brightness: Brightness.dark,
    bg: Color(0xFF1D2021),
    surface: Color(0xFF3C3836),
    surface2: Color(0xFF47423D),
    surfaceElevated: Color(0xFF47423D),
    fg: Color(0xFFD5C4A1),
    muted: Color(0xFFBDAE93),
    primary: Color(0xFFFABD2F),
    primaryHover: Color(0xFFF3BE46),
    primaryFg: Color(0xFF1D2021),
    primarySoft: Color(0xFFFACD5D),
    accent: Color(0xFF8EC07C),
    accentSoft: Color(0xFFAFCF93),
    accentFg: Color(0xFF1D2021),
    danger: Color(0xFFFB4934),
    success: Color(0xFFB8BB26),
    warning: Color(0xFFFABD2F),
  );

  /// Gruvbox — Dawid Kurek, morhetz.
  ///
  /// The classic: softer ground than Hard, same earth tones.
  ///
  /// Worst pairing: danger on surface at 3.67:1.
  static const AppPalette gruvboxDarkMedium = AppPalette(
    id: 'gruvbox_dark_medium',
    name: 'Gruvbox',
    description: 'The classic: softer ground than Hard, same earth tones.',
    author: 'Dawid Kurek, morhetz',
    brightness: Brightness.dark,
    bg: Color(0xFF282828),
    surface: Color(0xFF3C3836),
    surface2: Color(0xFF47423D),
    surfaceElevated: Color(0xFF47423D),
    fg: Color(0xFFD5C4A1),
    muted: Color(0xFFBDAE93),
    primary: Color(0xFFFABD2F),
    primaryHover: Color(0xFFF3BE46),
    primaryFg: Color(0xFF282828),
    primarySoft: Color(0xFFFACD5D),
    accent: Color(0xFF8EC07C),
    accentSoft: Color(0xFFAFCF93),
    accentFg: Color(0xFF282828),
    danger: Color(0xFFFB5A43),
    success: Color(0xFFB8BB26),
    warning: Color(0xFFFABD2F),
  );

  /// Gruvbox Material — Mayush Kumar, sainnhe.
  ///
  /// Gruvbox with the saturation pulled back for long sessions.
  ///
  /// Worst pairing: danger on surface at 4.19:1.
  static const AppPalette gruvboxMaterialDarkMedium = AppPalette(
    id: 'gruvbox_material_dark_medium',
    name: 'Gruvbox Material',
    description: 'Gruvbox with the saturation pulled back for long sessions.',
    author: 'Mayush Kumar, sainnhe',
    brightness: Brightness.dark,
    bg: Color(0xFF292828),
    surface: Color(0xFF32302F),
    surface2: Color(0xFF3E3B37),
    surfaceElevated: Color(0xFF3E3B37),
    fg: Color(0xFFDDC7A1),
    muted: Color(0xFFBDAE93),
    primary: Color(0xFF83B1A5),
    primaryHover: Color(0xFF95B5A4),
    primaryFg: Color(0xFF292828),
    primarySoft: Color(0xFFA7C4AF),
    accent: Color(0xFFD996A2),
    accentSoft: Color(0xFFE3B1AD),
    accentFg: Color(0xFF292828),
    danger: Color(0xFFEA6962),
    success: Color(0xFFA9B665),
    warning: Color(0xFFD8A657),
  );

  /// Nord — arcticicestudio.
  ///
  /// Arctic blue-greys with frost and aurora accents.
  ///
  /// Worst pairing: danger on surface at 3.72:1.
  static const AppPalette nord = AppPalette(
    id: 'nord',
    name: 'Nord',
    description: 'Arctic blue-greys with frost and aurora accents.',
    author: 'arcticicestudio',
    brightness: Brightness.dark,
    bg: Color(0xFF2E3440),
    surface: Color(0xFF3B4252),
    surface2: Color(0xFF434C5E),
    surfaceElevated: Color(0xFF434C5E),
    fg: Color(0xFFE5E9F0),
    muted: Color(0xFFB7BDC8),
    primary: Color(0xFFEBCB8B),
    primaryHover: Color(0xFFEAD19F),
    primaryFg: Color(0xFF2E3440),
    primarySoft: Color(0xFFEBD6AB),
    accent: Color(0xFF92C5D4),
    accentSoft: Color(0xFFADD2DE),
    accentFg: Color(0xFF2E3440),
    danger: Color(0xFFCD8C93),
    success: Color(0xFFA3BE8C),
    warning: Color(0xFFEBCB8B),
  );

  /// Dracula — clach04.
  ///
  /// Purple and pink on deep indigo. The famous one.
  ///
  /// Worst pairing: danger on surface at 3.93:1.
  static const AppPalette dracula = AppPalette(
    id: 'dracula',
    name: 'Dracula',
    description: 'Purple and pink on deep indigo. The famous one.',
    author: 'clach04',
    brightness: Brightness.dark,
    bg: Color(0xFF282A36),
    surface: Color(0xFF32343F),
    surface2: Color(0xFF40424C),
    surfaceElevated: Color(0xFF40424C),
    fg: Color(0xFFF8F8F2),
    muted: Color(0xFFA6AEC7),
    primary: Color(0xFFC49EFA),
    primaryHover: Color(0xFFCEB0F8),
    primaryFg: Color(0xFF282A36),
    primarySoft: Color(0xFFD6BBFC),
    accent: Color(0xFFFF86CC),
    accentSoft: Color(0xFFFFAADB),
    accentFg: Color(0xFF282A36),
    danger: Color(0xFFFF5555),
    success: Color(0xFF50FA7B),
    warning: Color(0xFFF1FA8C),
  );

  /// Catppuccin Mocha — catppuccin.
  ///
  /// Pastel mauve and sky on a soft near-black.
  ///
  /// Worst pairing: muted on surface2 at 4.68:1.
  static const AppPalette mocha = AppPalette(
    id: 'mocha',
    name: 'Catppuccin Mocha',
    description: 'Pastel mauve and sky on a soft near-black.',
    author: 'catppuccin',
    brightness: Brightness.dark,
    bg: Color(0xFF1E1E2E),
    surface: Color(0xFF272738),
    surface2: Color(0xFF313244),
    surfaceElevated: Color(0xFF313244),
    fg: Color(0xFFCDD6F4),
    muted: Color(0xFF979DB6),
    primary: Color(0xFF89B4FA),
    primaryHover: Color(0xFF97BBF9),
    primaryFg: Color(0xFF1E1E2E),
    primarySoft: Color(0xFFA9C1F1),
    accent: Color(0xFFCBA6F7),
    accentSoft: Color(0xFFD8B7EF),
    accentFg: Color(0xFF1E1E2E),
    danger: Color(0xFFF38BA8),
    success: Color(0xFFA6E3A1),
    warning: Color(0xFFF9E2AF),
  );

  /// Catppuccin Macchiato — catppuccin.
  ///
  /// Mocha's warmer, slightly lighter sibling.
  ///
  /// Worst pairing: muted on surface2 at 4.55:1.
  static const AppPalette catppuccinMacchiato = AppPalette(
    id: 'catppuccin_macchiato',
    name: 'Catppuccin Macchiato',
    description: "Mocha's warmer, slightly lighter sibling.",
    author: 'catppuccin',
    brightness: Brightness.dark,
    bg: Color(0xFF24273A),
    surface: Color(0xFF2C3043),
    surface2: Color(0xFF363A4F),
    surfaceElevated: Color(0xFF363A4F),
    fg: Color(0xFFCAD3F5),
    muted: Color(0xFF9DA4C2),
    primary: Color(0xFF8AADF4),
    primaryHover: Color(0xFF97B5F4),
    primaryFg: Color(0xFF24273A),
    primarySoft: Color(0xFFAABBEB),
    accent: Color(0xFFC6A0F6),
    accentSoft: Color(0xFFD4B2EC),
    accentFg: Color(0xFF24273A),
    danger: Color(0xFFED8796),
    success: Color(0xFFA6DA95),
    warning: Color(0xFFEED49F),
  );

  /// Rosé Pine — Emilia Dunfelt.
  ///
  /// Muted rose and pine on a deep plum night.
  ///
  /// Worst pairing: success on surface at 4.31:1.
  static const AppPalette rosePine = AppPalette(
    id: 'rose_pine',
    name: 'Rosé Pine',
    description: 'Muted rose and pine on a deep plum night.',
    author: 'Emilia Dunfelt',
    brightness: Brightness.dark,
    bg: Color(0xFF191724),
    surface: Color(0xFF1F1D2E),
    surface2: Color(0xFF26233A),
    surfaceElevated: Color(0xFF26233A),
    fg: Color(0xFFE0DEF4),
    muted: Color(0xFF908CAA),
    primary: Color(0xFFC4A7E7),
    primaryHover: Color(0xFFCAB2EA),
    primaryFg: Color(0xFF191724),
    primarySoft: Color(0xFFCCB8EB),
    accent: Color(0xFFF6C177),
    accentSoft: Color(0xFFEFCA9D),
    accentFg: Color(0xFF191724),
    danger: Color(0xFFEB6F92),
    success: Color(0xFF5489A3),
    warning: Color(0xFFEBBCBA),
  );

  /// Rosé Pine Moon — Emilia Dunfelt.
  ///
  /// Rosé Pine lifted off black, gentler at night.
  ///
  /// Worst pairing: success on surface at 4.17:1.
  static const AppPalette rosePineMoon = AppPalette(
    id: 'rose_pine_moon',
    name: 'Rosé Pine Moon',
    description: 'Rosé Pine lifted off black, gentler at night.',
    author: 'Emilia Dunfelt',
    brightness: Brightness.dark,
    bg: Color(0xFF232136),
    surface: Color(0xFF2A273F),
    surface2: Color(0xFF393552),
    surfaceElevated: Color(0xFF393552),
    fg: Color(0xFFE0DEF4),
    muted: Color(0xFFA7A4BD),
    primary: Color(0xFFC4A7E7),
    primaryHover: Color(0xFFCAB2EA),
    primaryFg: Color(0xFF232136),
    primarySoft: Color(0xFFCCB8EB),
    accent: Color(0xFFF6C177),
    accentSoft: Color(0xFFEFCA9D),
    accentFg: Color(0xFF232136),
    danger: Color(0xFFEB6F92),
    success: Color(0xFF4693B3),
    warning: Color(0xFFEA9A97),
  );

  /// Kanagawa — Tommaso Laurenzi.
  ///
  /// Ink-wash blues and dry gold, after Hokusai.
  ///
  /// Worst pairing: danger on surface at 4.13:1.
  static const AppPalette kanagawa = AppPalette(
    id: 'kanagawa',
    name: 'Kanagawa',
    description: 'Ink-wash blues and dry gold, after Hokusai.',
    author: 'Tommaso Laurenzi',
    brightness: Brightness.dark,
    bg: Color(0xFF1F1F28),
    surface: Color(0xFF28282F),
    surface2: Color(0xFF223249),
    surfaceElevated: Color(0xFF223249),
    fg: Color(0xFFDCD7BA),
    muted: Color(0xFF9F9C97),
    primary: Color(0xFF7E9CD8),
    primaryHover: Color(0xFF91A8D2),
    primaryFg: Color(0xFF1F1F28),
    primarySoft: Color(0xFF9AAECF),
    accent: Color(0xFFFFA066),
    accentSoft: Color(0xFFF5B17F),
    accentFg: Color(0xFF1F1F28),
    danger: Color(0xFFCB6D67),
    success: Color(0xFF76946A),
    warning: Color(0xFFC0A36E),
  );

  /// Everforest — Sainnhe Park.
  ///
  /// Low-saturation forest greens, easy on tired eyes.
  ///
  /// Worst pairing: danger on surface at 4.38:1.
  static const AppPalette everforest = AppPalette(
    id: 'everforest',
    name: 'Everforest',
    description: 'Low-saturation forest greens, easy on tired eyes.',
    author: 'Sainnhe Park',
    brightness: Brightness.dark,
    bg: Color(0xFF272E33),
    surface: Color(0xFF2E383C),
    surface2: Color(0xFF3A4244),
    surfaceElevated: Color(0xFF3A4244),
    fg: Color(0xFFD3C6AA),
    muted: Color(0xFFB0AF9B),
    primary: Color(0xFF7FBBB3),
    primaryHover: Color(0xFF90BDB1),
    primaryFg: Color(0xFF272E33),
    primarySoft: Color(0xFFA5CEC5),
    accent: Color(0xFFD89EB9),
    accentSoft: Color(0xFFE4BAC9),
    accentFg: Color(0xFF272E33),
    danger: Color(0xFFE67E80),
    success: Color(0xFFA7C080),
    warning: Color(0xFFDBBC7F),
  );

  /// Tokyo City — Michaël Ball.
  ///
  /// Neon-on-navy in the Tokyo Night lineage.
  ///
  /// Worst pairing: danger on surface at 5.87:1.
  static const AppPalette tokyoCityDark = AppPalette(
    id: 'tokyo_city_dark',
    name: 'Tokyo City',
    description: 'Neon-on-navy in the Tokyo Night lineage.',
    author: 'Michaël Ball',
    brightness: Brightness.dark,
    bg: Color(0xFF171D23),
    surface: Color(0xFF1D252C),
    surface2: Color(0xFF28323A),
    surfaceElevated: Color(0xFF28323A),
    fg: Color(0xFFD8E2EC),
    muted: Color(0xFFB7C5D3),
    primary: Color(0xFF7AA2F7),
    primaryHover: Color(0xFF8DAFF5),
    primaryFg: Color(0xFF171D23),
    primarySoft: Color(0xFFA1BDF9),
    accent: Color(0xFFBB9AF7),
    accentSoft: Color(0xFFCEB7F9),
    accentFg: Color(0xFF171D23),
    danger: Color(0xFFF7768E),
    success: Color(0xFF9ECE6A),
    warning: Color(0xFFB7C5D3),
  );

  /// Ayu Dark — Tinted Theming, Ayu Theme.
  ///
  /// Warm amber on charcoal — sharp and modern.
  ///
  /// Worst pairing: danger on surface at 6.26:1.
  static const AppPalette ayuDark = AppPalette(
    id: 'ayu_dark',
    name: 'Ayu Dark',
    description: 'Warm amber on charcoal — sharp and modern.',
    author: 'Tinted Theming, Ayu Theme',
    brightness: Brightness.dark,
    bg: Color(0xFF0B0E14),
    surface: Color(0xFF131721),
    surface2: Color(0xFF202229),
    surfaceElevated: Color(0xFF202229),
    fg: Color(0xFFE6E1CF),
    muted: Color(0xFFBFBDB6),
    primary: Color(0xFF59C2FF),
    primaryHover: Color(0xFF75C8F5),
    primaryFg: Color(0xFF0B0E14),
    primarySoft: Color(0xFF87D0F8),
    accent: Color(0xFFD2A6FF),
    accentSoft: Color(0xFFDCBCF8),
    accentFg: Color(0xFF0B0E14),
    danger: Color(0xFFF07178),
    success: Color(0xFFAAD94C),
    warning: Color(0xFFFFB454),
  );

  /// Ayu Mirage — Tinted Theming, Ayu Theme.
  ///
  /// Ayu on slate-blue, one stop lighter.
  ///
  /// Worst pairing: muted on surface2 at 4.77:1.
  static const AppPalette ayuMirage = AppPalette(
    id: 'ayu_mirage',
    name: 'Ayu Mirage',
    description: 'Ayu on slate-blue, one stop lighter.',
    author: 'Tinted Theming, Ayu Theme',
    brightness: Brightness.dark,
    bg: Color(0xFF1F2430),
    surface: Color(0xFF242936),
    surface2: Color(0xFF323844),
    surfaceElevated: Color(0xFF323844),
    fg: Color(0xFFCCCAC2),
    muted: Color(0xFFA5A5A3),
    primary: Color(0xFF73D0FF),
    primaryHover: Color(0xFF85CFF3),
    primaryFg: Color(0xFF1F2430),
    primarySoft: Color(0xFF99DBFC),
    accent: Color(0xFFD4BFFF),
    accentSoft: Color(0xFFDDCFFC),
    accentFg: Color(0xFF1F2430),
    danger: Color(0xFFF28779),
    success: Color(0xFFD5FF80),
    warning: Color(0xFFFFD173),
  );

  /// One Dark — olimorris.
  ///
  /// Atom's default, and half the internet's.
  ///
  /// Worst pairing: muted on surface2 at 4.66:1.
  static const AppPalette onedarkDark = AppPalette(
    id: 'onedark_dark',
    name: 'One Dark',
    description: "Atom's default, and half the internet's.",
    author: 'olimorris',
    brightness: Brightness.dark,
    bg: Color(0xFF000000),
    surface: Color(0xFF1C1F24),
    surface2: Color(0xFF26292F),
    surfaceElevated: Color(0xFF26292F),
    fg: Color(0xFFABB2BF),
    muted: Color(0xFF8C929E),
    primary: Color(0xFF61AFEF),
    primaryHover: Color(0xFF70B0E5),
    primaryFg: Color(0xFF000000),
    primarySoft: Color(0xFF80B8E7),
    accent: Color(0xFFD55FDE),
    accentSoft: Color(0xFFD180DB),
    accentFg: Color(0xFF000000),
    danger: Color(0xFFEF596F),
    success: Color(0xFF89CA78),
    warning: Color(0xFFE5C07B),
  );

  /// Monokai — Wimer Hazenberg.
  ///
  /// Sublime's green, pink and orange on graphite.
  ///
  /// Worst pairing: danger on surface at 3.69:1.
  static const AppPalette monokai = AppPalette(
    id: 'monokai',
    name: 'Monokai',
    description: "Sublime's green, pink and orange on graphite.",
    author: 'Wimer Hazenberg',
    brightness: Brightness.dark,
    bg: Color(0xFF272822),
    surface: Color(0xFF383830),
    surface2: Color(0xFF45453E),
    surfaceElevated: Color(0xFF45453E),
    fg: Color(0xFFF8F8F2),
    muted: Color(0xFFB7B5A8),
    primary: Color(0xFF66D9EF),
    primaryHover: Color(0xFF83DFF0),
    primaryFg: Color(0xFF272822),
    primarySoft: Color(0xFF92E2F1),
    accent: Color(0xFFFD9C2A),
    accentSoft: Color(0xFFFCB867),
    accentFg: Color(0xFF272822),
    danger: Color(0xFFF9508C),
    success: Color(0xFFA6E22E),
    warning: Color(0xFFF4BF75),
  );

  /// Material — Nate Peterson.
  ///
  /// Teal and coral on true dark grey.
  ///
  /// Worst pairing: danger on surface at 4.61:1.
  static const AppPalette materialDarker = AppPalette(
    id: 'material_darker',
    name: 'Material',
    description: 'Teal and coral on true dark grey.',
    author: 'Nate Peterson',
    brightness: Brightness.dark,
    bg: Color(0xFF212121),
    surface: Color(0xFF303030),
    surface2: Color(0xFF353535),
    surfaceElevated: Color(0xFF353535),
    fg: Color(0xFFEEFFFF),
    muted: Color(0xFFB2CCD6),
    primary: Color(0xFF82AAFF),
    primaryHover: Color(0xFF98BBFF),
    primaryFg: Color(0xFF212121),
    primarySoft: Color(0xFFA8C4FF),
    accent: Color(0xFFC792EA),
    accentSoft: Color(0xFFD8B3F0),
    accentFg: Color(0xFF212121),
    danger: Color(0xFFF07178),
    success: Color(0xFFC3E88D),
    warning: Color(0xFFFFCB6B),
  );

  /// GitHub Dark — Tinted Theming.
  ///
  /// GitHub's own dark mode, familiar and neutral.
  ///
  /// Worst pairing: muted on surface2 at 4.82:1.
  static const AppPalette githubDark = AppPalette(
    id: 'github_dark',
    name: 'GitHub Dark',
    description: "GitHub's own dark mode, familiar and neutral.",
    author: 'Tinted Theming',
    brightness: Brightness.dark,
    bg: Color(0xFF0D1117),
    surface: Color(0xFF161B22),
    surface2: Color(0xFF23282F),
    surfaceElevated: Color(0xFF23282F),
    fg: Color(0xFFC9D1D9),
    muted: Color(0xFF8B949E),
    primary: Color(0xFFD2A8FF),
    primaryHover: Color(0xFFD0B0F7),
    primaryFg: Color(0xFF0D1117),
    primarySoft: Color(0xFFE0C2FF),
    accent: Color(0xFFFF7B72),
    accentSoft: Color(0xFFFFA39C),
    accentFg: Color(0xFF0D1117),
    danger: Color(0xFFFFA657),
    success: Color(0xFFA5D6FF),
    warning: Color(0xFFBB8009),
  );

  /// Flexoki Dark — Steph Ango.
  ///
  /// Ink-and-paper pigments tuned for E Ink.
  ///
  /// Worst pairing: danger on surface at 4.26:1.
  static const AppPalette flexokiDark = AppPalette(
    id: 'flexoki_dark',
    name: 'Flexoki Dark',
    description: 'Ink-and-paper pigments tuned for E Ink.',
    author: 'Steph Ango',
    brightness: Brightness.dark,
    bg: Color(0xFF100F0F),
    surface: Color(0xFF1C1B1A),
    surface2: Color(0xFF282726),
    surfaceElevated: Color(0xFF282726),
    fg: Color(0xFFCECDC3),
    muted: Color(0xFF93928B),
    primary: Color(0xFF5F97C6),
    primaryHover: Color(0xFF75A2C5),
    primaryFg: Color(0xFF100F0F),
    primarySoft: Color(0xFF8FB5D3),
    accent: Color(0xFF9184CA),
    accentSoft: Color(0xFFB2A8D5),
    accentFg: Color(0xFF100F0F),
    danger: Color(0xFFD3564A),
    success: Color(0xFF879A39),
    warning: Color(0xFFD0A215),
  );

  /// Oxocarbon — shaunsingh/IBM, Tinted Theming.
  ///
  /// IBM Carbon — cool blue with electric magenta.
  ///
  /// Worst pairing: danger on surface at 4.55:1.
  static const AppPalette oxocarbonDark = AppPalette(
    id: 'oxocarbon_dark',
    name: 'Oxocarbon',
    description: 'IBM Carbon — cool blue with electric magenta.',
    author: 'shaunsingh/IBM, Tinted Theming',
    brightness: Brightness.dark,
    bg: Color(0xFF161616),
    surface: Color(0xFF262626),
    surface2: Color(0xFF343435),
    surfaceElevated: Color(0xFF343435),
    fg: Color(0xFFF2F4F8),
    muted: Color(0xFFA2A3A5),
    primary: Color(0xFF33B1FF),
    primaryHover: Color(0xFF59BEFE),
    primaryFg: Color(0xFF161616),
    primarySoft: Color(0xFF70C8FF),
    accent: Color(0xFFBE95FF),
    accentSoft: Color(0xFFD2B5FF),
    accentFg: Color(0xFF161616),
    danger: Color(0xFFEE5396),
    success: Color(0xFF42BE65),
    warning: Color(0xFFFF6F00),
  );

  /// Spaceduck — Guillermo Rodriguez, packaged by Gabriel Fontes.
  ///
  /// Deep space navy with cyan and violet instruments.
  ///
  /// Worst pairing: danger on surface at 4.45:1.
  static const AppPalette spaceduck = AppPalette(
    id: 'spaceduck',
    name: 'Spaceduck',
    description: 'Deep space navy with cyan and violet instruments.',
    author: 'Guillermo Rodriguez, packaged by Gabriel Fontes',
    brightness: Brightness.dark,
    bg: Color(0xFF16172D),
    surface: Color(0xFF1B1C36),
    surface2: Color(0xFF2A2B40),
    surfaceElevated: Color(0xFF2A2B40),
    fg: Color(0xFFECF0C1),
    muted: Color(0xFF9096A6),
    primary: Color(0xFFF2CE00),
    primaryHover: Color(0xFFF1D527),
    primaryFg: Color(0xFF16172D),
    primarySoft: Color(0xFFF6DD4D),
    accent: Color(0xFFB3A1E6),
    accentSoft: Color(0xFFCABDEE),
    accentFg: Color(0xFF16172D),
    danger: Color(0xFFE75226),
    success: Color(0xFF5CCC96),
    warning: Color(0xFFF2CE00),
  );

  /// Eldritch — eldritch-theme.
  ///
  /// Occult greens and purples on abyssal blue.
  ///
  /// Worst pairing: danger on surface at 4.15:1.
  static const AppPalette eldritch = AppPalette(
    id: 'eldritch',
    name: 'Eldritch',
    description: 'Occult greens and purples on abyssal blue.',
    author: 'eldritch-theme',
    brightness: Brightness.dark,
    bg: Color(0xFF212337),
    surface: Color(0xFF323449),
    surface2: Color(0xFF3F4255),
    surfaceElevated: Color(0xFF3F4255),
    fg: Color(0xFFEBFAFA),
    muted: Color(0xFFA1B1E1),
    primary: Color(0xFF39DDFD),
    primaryHover: Color(0xFF5DE3FC),
    primaryFg: Color(0xFF212337),
    primarySoft: Color(0xFF74E7FE),
    accent: Color(0xFFF7C67F),
    accentSoft: Color(0xFFF9D7A5),
    accentFg: Color(0xFF212337),
    danger: Color(0xFFF16C75),
    success: Color(0xFF37F499),
    warning: Color(0xFFF1FC79),
  );

  /// Selenized Black — Jan Warchol / adapted to base16 by ali.
  ///
  /// Solarized's successor, rebuilt for true black.
  ///
  /// Worst pairing: danger on surface at 4.14:1.
  static const AppPalette selenizedBlack = AppPalette(
    id: 'selenized_black',
    name: 'Selenized Black',
    description: "Solarized's successor, rebuilt for true black.",
    author: 'Jan Warchol / adapted to base16 by ali',
    brightness: Brightness.dark,
    bg: Color(0xFF181818),
    surface: Color(0xFF252525),
    surface2: Color(0xFF2F2F2F),
    surfaceElevated: Color(0xFF2F2F2F),
    fg: Color(0xFFB9B9B9),
    muted: Color(0xFF989898),
    primary: Color(0xFFDBB32D),
    primaryHover: Color(0xFFD4B449),
    primaryFg: Color(0xFF181818),
    primarySoft: Color(0xFFDCC062),
    accent: Color(0xFFA885E2),
    accentSoft: Color(0xFFB8A0E1),
    accentFg: Color(0xFF181818),
    danger: Color(0xFFED4A46),
    success: Color(0xFF70B433),
    warning: Color(0xFFDBB32D),
  );

  /// Horizon Dark — Michaël Ball.
  ///
  /// Dusk pinks and corals over a warm slate.
  ///
  /// Worst pairing: danger on surface at 4.13:1.
  static const AppPalette horizonDark = AppPalette(
    id: 'horizon_dark',
    name: 'Horizon Dark',
    description: 'Dusk pinks and corals over a warm slate.',
    author: 'Michaël Ball',
    brightness: Brightness.dark,
    bg: Color(0xFF1C1E26),
    surface: Color(0xFF232530),
    surface2: Color(0xFF2E303E),
    surfaceElevated: Color(0xFF2E303E),
    fg: Color(0xFFCBCED0),
    muted: Color(0xFF9DA0A2),
    primary: Color(0xFFEFB993),
    primaryHover: Color(0xFFE8BD9F),
    primaryFg: Color(0xFF1C1E26),
    primarySoft: Color(0xFFEBC7AE),
    accent: Color(0xFFB883D5),
    accentSoft: Color(0xFFC5A1DD),
    accentFg: Color(0xFF1C1E26),
    danger: Color(0xFFE84D67),
    success: Color(0xFFEFAF8E),
    warning: Color(0xFFEFB993),
  );

  /// Zenburn — elnawe.
  ///
  /// The low-contrast original: sage and rust on grey.
  ///
  /// Worst pairing: success on surface at 4.28:1.
  static const AppPalette zenburn = AppPalette(
    id: 'zenburn',
    name: 'Zenburn',
    description: 'The low-contrast original: sage and rust on grey.',
    author: 'elnawe',
    brightness: Brightness.dark,
    bg: Color(0xFF383838),
    surface: Color(0xFF404040),
    surface2: Color(0xFF4B4B4A),
    surfaceElevated: Color(0xFF4B4B4A),
    fg: Color(0xFFDCDCCC),
    muted: Color(0xFFBBBBB0),
    primary: Color(0xFFE0CF9F),
    primaryHover: Color(0xFFDFD2A8),
    primaryFg: Color(0xFF383838),
    primarySoft: Color(0xFFE9DDBC),
    accent: Color(0xFF93E0E3),
    accentSoft: Color(0xFFB3E9EB),
    accentFg: Color(0xFF383838),
    danger: Color(0xFFDCA3A3),
    success: Color(0xFF97AC97),
    warning: Color(0xFFE0CF9F),
  );

  /// Vesper — FormalSnake.
  ///
  /// Near-monochrome graphite with a single amber note.
  ///
  /// Worst pairing: success on surface at 3.97:1.
  static const AppPalette vesper = AppPalette(
    id: 'vesper',
    name: 'Vesper',
    description: 'Near-monochrome graphite with a single amber note.',
    author: 'FormalSnake',
    brightness: Brightness.dark,
    bg: Color(0xFF101010),
    surface: Color(0xFF232323),
    surface2: Color(0xFF2D2D2D),
    surfaceElevated: Color(0xFF2D2D2D),
    fg: Color(0xFFB7B7B7),
    muted: Color(0xFF999999),
    primary: Color(0xFF8EAAAA),
    primaryHover: Color(0xFF96ADAD),
    primaryFg: Color(0xFF101010),
    primarySoft: Color(0xFFA3B7B7),
    accent: Color(0xFFD69094),
    accentSoft: Color(0xFFD6A5A8),
    accentFg: Color(0xFF101010),
    danger: Color(0xFFDE6E6E),
    success: Color(0xFF5F8787),
    warning: Color(0xFFFFC799),
  );

  /// Catppuccin Latte — catppuccin.
  ///
  /// Pastel accents on cool porcelain.
  ///
  /// Worst pairing: warning on bg at 4.52:1.
  static const AppPalette latte = AppPalette(
    id: 'latte',
    name: 'Catppuccin Latte',
    description: 'Pastel accents on cool porcelain.',
    author: 'catppuccin',
    brightness: Brightness.light,
    bg: Color(0xFFEFF1F5),
    surface: Color(0xFFF5F6F9),
    surface2: Color(0xFFFBFBFC),
    surfaceElevated: Color(0xFFFBFBFC),
    fg: Color(0xFF4C4F69),
    muted: Color(0xFF686B82),
    primary: Color(0xFF2364E7),
    primaryHover: Color(0xFF2B60CE),
    primaryFg: Color(0xFFEFF1F5),
    primarySoft: Color(0xFF2F5EC1),
    accent: Color(0xFF8839EF),
    accentSoft: Color(0xFF7640C7),
    accentFg: Color(0xFFEFF1F5),
    danger: Color(0xFFD20F39),
    success: Color(0xFF46784A),
    warning: Color(0xFF87684B),
  );

  /// Rosé Pine Dawn — Emilia Dunfelt.
  ///
  /// Warm blush paper with muted rose ink.
  ///
  /// Worst pairing: warning on bg at 4.55:1.
  static const AppPalette dawn = AppPalette(
    id: 'dawn',
    name: 'Rosé Pine Dawn',
    description: 'Warm blush paper with muted rose ink.',
    author: 'Emilia Dunfelt',
    brightness: Brightness.light,
    bg: Color(0xFFFAF4ED),
    surface: Color(0xFFFCF8F3),
    surface2: Color(0xFFFEFCFA),
    surfaceElevated: Color(0xFFFEFCFA),
    fg: Color(0xFF575279),
    muted: Color(0xFF716C8B),
    primary: Color(0xFF286983),
    primaryHover: Color(0xFF316481),
    primaryFg: Color(0xFFFAF4ED),
    primarySoft: Color(0xFF366280),
    accent: Color(0xFF985E7A),
    accentSoft: Color(0xFF855A7A),
    accentFg: Color(0xFFFAF4ED),
    danger: Color(0xFF985E7A),
    success: Color(0xFF286983),
    warning: Color(0xFF8A657B),
  );

  /// Gruvbox Light — Dawid Kurek, morhetz.
  ///
  /// Cream paper, earth-tone ink.
  ///
  /// Worst pairing: success on bg at 4.54:1.
  static const AppPalette gruvboxLightMedium = AppPalette(
    id: 'gruvbox_light_medium',
    name: 'Gruvbox Light',
    description: 'Cream paper, earth-tone ink.',
    author: 'Dawid Kurek, morhetz',
    brightness: Brightness.light,
    bg: Color(0xFFFBF1C7),
    surface: Color(0xFFFCF6DB),
    surface2: Color(0xFFFEFBEF),
    surfaceElevated: Color(0xFFFEFBEF),
    fg: Color(0xFF504945),
    muted: Color(0xFF665C54),
    primary: Color(0xFF076678),
    primaryHover: Color(0xFF16606E),
    primaryFg: Color(0xFFFBF1C7),
    primarySoft: Color(0xFF115360),
    accent: Color(0xFF8F3F71),
    accentSoft: Color(0xFF70385B),
    accentFg: Color(0xFFFBF1C7),
    danger: Color(0xFF9D0006),
    success: Color(0xFF75700F),
    warning: Color(0xFF926319),
  );

  /// One Light — Daniel Pfeifer.
  ///
  /// One Dark inverted — crisp, neutral, familiar.
  ///
  /// Worst pairing: warning on surface at 4.53:1.
  static const AppPalette oneLight = AppPalette(
    id: 'one_light',
    name: 'One Light',
    description: 'One Dark inverted — crisp, neutral, familiar.',
    author: 'Daniel Pfeifer',
    brightness: Brightness.light,
    bg: Color(0xFFFAFAFA),
    surface: Color(0xFFF2F2F3),
    surface2: Color(0xFFEAEAEA),
    surfaceElevated: Color(0xFFEAEAEA),
    fg: Color(0xFF383A42),
    muted: Color(0xFF67686F),
    primary: Color(0xFFA626A4),
    primaryHover: Color(0xFF902A90),
    primaryFg: Color(0xFFFAFAFA),
    primarySoft: Color(0xFF771E76),
    accent: Color(0xFFCA1243),
    accentSoft: Color(0xFF901032),
    accentFg: Color(0xFFFAFAFA),
    danger: Color(0xFFCA1243),
    success: Color(0xFF3E7B3E),
    warning: Color(0xFF936604),
  );

  /// GitHub Light — Tinted Theming.
  ///
  /// GitHub's default: plain white and a confident blue.
  ///
  /// Worst pairing: warning on surface at 4.34:1.
  static const AppPalette github = AppPalette(
    id: 'github',
    name: 'GitHub Light',
    description: "GitHub's default: plain white and a confident blue.",
    author: 'Tinted Theming',
    brightness: Brightness.light,
    bg: Color(0xFFFFFFFF),
    surface: Color(0xFFF7F8F8),
    surface2: Color(0xFFEFF0F0),
    surfaceElevated: Color(0xFFEFF0F0),
    fg: Color(0xFF424A53),
    muted: Color(0xFF636C75),
    primary: Color(0xFF7D4ED6),
    primaryHover: Color(0xFF714DBC),
    primaryFg: Color(0xFFFFFFFF),
    primarySoft: Color(0xFF6141A2),
    accent: Color(0xFFCF222E),
    accentSoft: Color(0xFF9A222C),
    accentFg: Color(0xFFFFFFFF),
    danger: Color(0xFF953800),
    success: Color(0xFF0A3069),
    warning: Color(0xFF976E0A),
  );

  /// Flexoki Light — Steph Ango.
  ///
  /// Warm paper pigments; the E Ink palette by daylight.
  ///
  /// Worst pairing: success on surface at 4.43:1.
  static const AppPalette flexokiLight = AppPalette(
    id: 'flexoki_light',
    name: 'Flexoki Light',
    description: 'Warm paper pigments; the E Ink palette by daylight.',
    author: 'Steph Ango',
    brightness: Brightness.light,
    bg: Color(0xFFFFFCF0),
    surface: Color(0xFFF7F4E9),
    surface2: Color(0xFFEFECE1),
    surfaceElevated: Color(0xFFEFECE1),
    fg: Color(0xFF403E3C),
    muted: Color(0xFF6B6965),
    primary: Color(0xFF205EA6),
    primaryHover: Color(0xFF265891),
    primaryFg: Color(0xFFFFFCF0),
    primarySoft: Color(0xFF1B4679),
    accent: Color(0xFF5E409D),
    accentSoft: Color(0xFF473172),
    accentFg: Color(0xFFFFFCF0),
    danger: Color(0xFFAF3029),
    success: Color(0xFF627A0B),
    warning: Color(0xFF8E6C04),
  );

  /// Nord Light — threddast, based on fuxialexander's doom-nord-light-theme (Doom Emacs).
  ///
  /// Arctic blues on snow.
  ///
  /// Worst pairing: primary on bg at 4.52:1.
  static const AppPalette nordLight = AppPalette(
    id: 'nord_light',
    name: 'Nord Light',
    description: 'Arctic blues on snow.',
    author: "threddast, based on fuxialexander's doom-nord-light-theme (Doom Emacs)",
    brightness: Brightness.light,
    bg: Color(0xFFE5E9F0),
    surface: Color(0xFFEEF1F5),
    surface2: Color(0xFFF8F9FB),
    surfaceElevated: Color(0xFFF8F9FB),
    fg: Color(0xFF2E3440),
    muted: Color(0xFF5B6372),
    primary: Color(0xFF3A6BA3),
    primaryHover: Color(0xFF38608F),
    primaryFg: Color(0xFFE5E9F0),
    primarySoft: Color(0xFF365B85),
    accent: Color(0xFF97365B),
    accentSoft: Color(0xFF783553),
    accentFg: Color(0xFFE5E9F0),
    danger: Color(0xFF99324B),
    success: Color(0xFF457048),
    warning: Color(0xFF7F6510),
  );

  /// Tokyo Night Light — Michaël Ball.
  ///
  /// The night city at noon — indigo ink on white.
  ///
  /// Worst pairing: warning on bg at 4.73:1.
  static const AppPalette tokyoNightLight = AppPalette(
    id: 'tokyo_night_light',
    name: 'Tokyo Night Light',
    description: 'The night city at noon — indigo ink on white.',
    author: 'Michaël Ball',
    brightness: Brightness.light,
    bg: Color(0xFFD5D6DB),
    surface: Color(0xFFE4E4E8),
    surface2: Color(0xFFF3F4F5),
    surfaceElevated: Color(0xFFF3F4F5),
    fg: Color(0xFF343B59),
    muted: Color(0xFF4C505E),
    primary: Color(0xFF34548A),
    primaryHover: Color(0xFF344F80),
    primaryFg: Color(0xFFD5D6DB),
    primarySoft: Color(0xFF2C436C),
    accent: Color(0xFF5A4A78),
    accentSoft: Color(0xFF473C5F),
    accentFg: Color(0xFFD5D6DB),
    danger: Color(0xFF343B58),
    success: Color(0xFF485E30),
    warning: Color(0xFF166371),
  );

  /// Selenized White — Jan Warchol / adapted to base16 by ali.
  ///
  /// Solarized's successor at full brightness.
  ///
  /// Worst pairing: warning on surface at 4.53:1.
  static const AppPalette selenizedWhite = AppPalette(
    id: 'selenized_white',
    name: 'Selenized White',
    description: "Solarized's successor at full brightness.",
    author: 'Jan Warchol / adapted to base16 by ali',
    brightness: Brightness.light,
    bg: Color(0xFFFFFFFF),
    surface: Color(0xFFF8F8F8),
    surface2: Color(0xFFEFEFEF),
    surfaceElevated: Color(0xFFEFEFEF),
    fg: Color(0xFF474747),
    muted: Color(0xFF6A6A6A),
    primary: Color(0xFF0054CF),
    primaryHover: Color(0xFF0E51B4),
    primaryFg: Color(0xFFFFFFFF),
    primarySoft: Color(0xFF0C479D),
    accent: Color(0xFF6B40C3),
    accentSoft: Color(0xFF573995),
    accentFg: Color(0xFFFFFFFF),
    danger: Color(0xFFBF0000),
    success: Color(0xFF008400),
    warning: Color(0xFF8D6E0A),
  );

  /// Equilibrium Light — Carlo Abelli.
  ///
  /// Warm oat paper balanced against a cool blue.
  ///
  /// Worst pairing: success on bg at 4.70:1.
  static const AppPalette equilibriumLight = AppPalette(
    id: 'equilibrium_light',
    name: 'Equilibrium Light',
    description: 'Warm oat paper balanced against a cool blue.',
    author: 'Carlo Abelli',
    brightness: Brightness.light,
    bg: Color(0xFFF5F0E7),
    surface: Color(0xFFF9F5EF),
    surface2: Color(0xFFFCFBF8),
    surfaceElevated: Color(0xFFFCFBF8),
    fg: Color(0xFF43474E),
    muted: Color(0xFF5A5F66),
    primary: Color(0xFF016FAE),
    primaryHover: Color(0xFF0E679B),
    primaryFg: Color(0xFFF5F0E7),
    primarySoft: Color(0xFF085684),
    accent: Color(0xFFBF3E05),
    accentSoft: Color(0xFF8D340E),
    accentFg: Color(0xFFF5F0E7),
    danger: Color(0xFFD02023),
    success: Color(0xFF637200),
    warning: Color(0xFF896305),
  );

  /// Horizon Light — Michaël Ball.
  ///
  /// Dawn corals and pinks on warm off-white.
  ///
  /// Worst pairing: primary on bg at 4.57:1.
  static const AppPalette horizonLight = AppPalette(
    id: 'horizon_light',
    name: 'Horizon Light',
    description: 'Dawn corals and pinks on warm off-white.',
    author: 'Michaël Ball',
    brightness: Brightness.light,
    bg: Color(0xFFFDF0ED),
    surface: Color(0xFFFEF5F3),
    surface2: Color(0xFFFEFBFA),
    surfaceElevated: Color(0xFFFEFBFA),
    fg: Color(0xFF403C3D),
    muted: Color(0xFF726C6B),
    primary: Color(0xFFDA103F),
    primaryHover: Color(0xFFBB193F),
    primaryFg: Color(0xFFFDF0ED),
    primarySoft: Color(0xFFA21435),
    accent: Color(0xFF1D7980),
    accentSoft: Color(0xFF1E5D62),
    accentFg: Color(0xFFFDF0ED),
    danger: Color(0xFF965D62),
    success: Color(0xFF54755F),
    warning: Color(0xFF786A68),
  );

  /// Sakura — Misterio77.
  ///
  /// Blossom pink paper with deep teal ink.
  ///
  /// Worst pairing: danger on bg at 4.53:1.
  static const AppPalette sakura = AppPalette(
    id: 'sakura',
    name: 'Sakura',
    description: 'Blossom pink paper with deep teal ink.',
    author: 'Misterio77',
    brightness: Brightness.light,
    bg: Color(0xFFFEEDF3),
    surface: Color(0xFFFEF3F7),
    surface2: Color(0xFFFFFAFC),
    surfaceElevated: Color(0xFFFFFAFC),
    fg: Color(0xFF564448),
    muted: Color(0xFF755F64),
    primary: Color(0xFF006E93),
    primaryHover: Color(0xFF116684),
    primaryFg: Color(0xFFFEEDF3),
    primarySoft: Color(0xFF0F5974),
    accent: Color(0xFF5E2180),
    accentSoft: Color(0xFF512367),
    accentFg: Color(0xFFFEEDF3),
    danger: Color(0xFFCE2D4E),
    success: Color(0xFF2F775D),
    warning: Color(0xFF826449),
  );

  /// Dark schemes, in the order the web curates them (families adjacent).
  static const List<AppPalette> dark = [
    gruvbox,
    gruvboxDarkMedium,
    gruvboxMaterialDarkMedium,
    nord,
    dracula,
    mocha,
    catppuccinMacchiato,
    rosePine,
    rosePineMoon,
    kanagawa,
    everforest,
    tokyoCityDark,
    ayuDark,
    ayuMirage,
    onedarkDark,
    monokai,
    materialDarker,
    githubDark,
    flexokiDark,
    oxocarbonDark,
    spaceduck,
    eldritch,
    selenizedBlack,
    horizonDark,
    zenburn,
    vesper,
  ];

  /// Light schemes, same order.
  static const List<AppPalette> light = [
    latte,
    dawn,
    gruvboxLightMedium,
    oneLight,
    github,
    flexokiLight,
    nordLight,
    tokyoNightLight,
    selenizedWhite,
    equilibriumLight,
    horizonLight,
    sakura,
  ];

}
